version: "3"

services:
  mysqldb:
    container_name: mysql8
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
  app:
    depends_on:
      - mysqldb
    image: baherammari/app-spring-repo
    restart: always
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysql8
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  db:
