version: "3"
services:

  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - devops_network

  backend_app:
    image: mouhibtouaiti/project-devop:latest
    container_name: backend_app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.generate-ddl" : "true",
        "server.port" : "8082",
        "spring.main.allow-circular-references" : "true"
          }'
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    restart: on-failure
    stdin_open: true
    tty: true

    networks:
      - devops_network

#  frontend_app:
#    image:
#


networks:
  devops_network:

volumes:
  db_vol: