version: "3"
services:
  mysql_db:
    image: mysql
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=mouhibjenkins
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - devops_network

  backend_app:
    image: mouhibtouaiti/project-devop:latest
    container_name: backend_app
    environment:
      - spring.datasource.url=jdbc:mysql://172.17.0.3:3306/mouhibjenkins?createDatabaseIfNotExist=true
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=mouhibjenkins
    ports:
      - "8082:8082"
    depends_on:
      - mysql_db
    restart: on-failure
    networks:
      - devops_network

#  frontend_app:
#    image:
#


networks:
  devops_network:

volumes:
  db_vol: