version: "3"
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - devops_network
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    networks:
      - devops_network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - devops_network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - devops_network
    depends_on:
      - prometheus
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mouhibjenkins
    ports:
      - "3306:3306"
    networks:
      - devops_network


networks:
  devops_network:
